# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 6c8620899e0615be1ea24d1048cbc93f1513b8ee

###

GET {{baseUrl}}/advertisements/favorites
Content-Type: application/json
Authorization: Token 6c8620899e0615be1ea24d1048cbc93f1513b8ee

###
# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token af5271a01b85647f3b5d9d21b2cee052d4422c20

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token 6c8620899e0615be1ea24d1048cbc93f1513b8ee

{
  "status": "CLOSED"
}
#####

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
Authorization: Token 6c8620899e0615be1ea24d1048cbc93f1513b8ee

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
Authorization: Token 6c8620899e0615be1ea24d1048cbc93f1513b8ee
